version: "3"
services:
  elasticsearch:
    # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
    container_name: elasticsearch
    hostname: elasticsearch
    image: elastic/elasticsearch:7.16.3
    environment:
      - discovery.type=single-node
      - XPACK_SECURITY_ENABLED=true
      - ELASTIC_PASSWORD="123456"
      # - KEYSTORE_PASSWORD="123456"
    ports:
      - "9200:9200"
    networks:
      - elastinet
    restart: on-failure:5
    volumes:
      - ./elastic/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh:ro
      - ./elastic/data:/usr/share/elasticsearch/data
      - ./elastic/config:/usr/share/elasticsearch/config:rw

  kibana:
    # 
    container_name: kibana
    hostname: kibana
    image: elastic/kibana:7.16.3
    environment:
      - xpack.reporting.enabled=false
      - ELASTICSEARCH_USERNAME="elastic"
      - ELASTICSEARCH_PASSWORD="123456"
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    networks:
      - elastinet
    volumes:
      - ./kibana/config:/usr/share/kibana/config/:rw
    restart: on-failure:5

  filebeat:
    container_name: filebeat
    hostname: filebeat
    depends_on:
      - kibana
    image: elastic/filebeat:7.16.3
    links:
      - kibana
      - elasticsearch
    volumes:
      - ./zeek/log:/pcap
      - ./filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml
    command: -e
    networks:
      - elastinet
    restart: on-failure:5
    environment:
      - ELASTICSEARCH_USERNAME="elastic"
      - ELASTICSEARCH_PASSWORD="123456"

  zeek:
    container_name: zeek
    hostname: zeek
    depends_on:
      - filebeat
    image: xrsec/zeek
    volumes:
      - ./zeek/log:/pcap
      - ./zeek/local.zeek:/usr/local/zeek/share/zeek/site/local.zeek:rw
    cap_add:
      - NET_RAW
    network_mode: "host"
    command: -i eth0
    restart: on-failure:5

networks: 
  elastinet: