version: "3"
services:
  elasticsearch:
    container_name: elasticsearch
    hostname: elasticsearch
    image: xrsec/zeek:elastic
    environment:
      - discovery.type=single-node
      - elastic_pass="123456"
    ports:
      - "9200:9200"
    networks:
      - elastinet
    restart: on-failure:5
    volumes:
      - ./elastic/entrypoint.sh:/usr/local/bin/entrypoint:ro
      - ./elastic/data:/usr/share/elasticsearch/data
      - ./elastic/config/elasticsearch.yml:/etc/elasticsearch/elasticsearch.yml:rw

  kibana:
    container_name: kibana
    hostname: kibana
    image: xrsec/zeek:kibana
    environment:
      - xpack.reporting.enabled=false
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    networks:
      - elastinet
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:rw
    restart: on-failure:5

  filebeat:
    container_name: filebeat
    hostname: filebeat
    depends_on:
      - kibana
    image: xrsec/zeek:filebeat
    links:
      - kibana
      - elasticsearch
    volumes:
      - ./zeek/log:/pcap
      - ./filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml
    command: -e
    networks:
      - elastinet
    restart: on-failure:5
    # environment:
    #   - ELASTICSEARCH_USERNAME="elastic"
    #   - ELASTICSEARCH_PASSWORD="123456"

  zeek:
    container_name: zeek
    hostname: zeek
    depends_on:
      - filebeat
    image: xrsec/zeek
    volumes:
      - ./zeek/log:/pcap
    cap_add:
      - NET_RAW
    network_mode: "host"
    command: -i eth1
    restart: on-failure:5

networks: 
  elastinet:
